export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: 'Code Hub',
    headline: 'Make it work, make it right, make it fast.',
    description: 'Discover great coding/programming tutorials from awesome developers all around the world for free',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/pair_programming.svg'),
    alt: 'Programming',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Code Hub',
    headline: 'Make it work, make it right, make it fast.',
    description: 'Discover great coding/programming tutorials from awesome developers all around the world for free',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/pair_programming.svg'),
    alt: 'Programming',
    dark: true,
    primary: true,
    darkText: true,
}

export const homeObjThree = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: 'Code Hub',
    headline: 'Make it work, make it right, make it fast.',
    description: 'Discover great coding/programming tutorials from awesome developers all around the world for free',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/pair_programming.svg'),
    alt: 'Programming',
    dark: true,
    primary: true,
    darkText: true,
}